### ISSUE TITLE
how we can download theme for first time?

### ISSUE THREAD

**Issue by hosseinabdollahzadeh** [arminamirinasab/Free-Internet#1]
how we can download theme for first time when we face with this message:
This site can’t be reached
:|

**Comment by arminamirinasab** [comment]
Hi Dear Hossein.
For Download There You Need a VPN , In This Repository I Only Introuduce Good VPNS For Access To Free Internet , I Recommend You To Use Chedot Browser With Built In Proxy , It's Good Way For Download VPN.
[Paskoocheh](https://paskoocheh.com) Is Persian Website To Download VPN
